### ISSUE TITLE
Unhandled exception when using Plugin RpcServer

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#198]
```cs
neo> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.ResponseCompression, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.ResponseCompression, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Neo.Plugins.RpcServer.<>c.<OnPluginsLoaded>b__20_2(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Neo.Plugins.RpcServer.OnPluginsLoaded()
   at Neo.NeoSystem..ctor(String storageEngine) in /opt/neoLib/src/neo/NeoSystem.cs:line 39
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by shargon** [comment]
We will need dependecies in plugins

**Comment by vncoelho** [comment]
Do you know which dependencies to install, @shargon?
Currently this problem is blocking the use on Ubuntu Bionic.

**Comment by vncoelho** [comment]
I read about adding `<PackageReference Include="Microsoft.AspNetCore.App" />`, however, I had problem of compatibility with `netstandard2.1`.

**Comment by shargon** [comment]
It should be `Microsoft.AspNetCore.ResponseCompression`

**Comment by vncoelho** [comment]
` error NU1202: Package Microsoft.AspNetCore.App 2.1.1 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.AspNetCore.App 2.1.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)`

I did not understand what you mean, @shargon.

**Comment by shargon** [comment]
If you publish the module, and copy `Microsoft.AspNetCore.ResponseCompression.dll` to neo-cli path, i think that it should work, but it's something to fix it

**Comment by vncoelho** [comment]
I am not being able to find this `Microsoft.AspNetCore.ResponseCompression.dll` after publishing the module. In which folder is it supposed to be?

**Comment by vncoelho** [comment]
I needed to include this on the .csproj:

```cs
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```

In order to have access to the .dll after publish.

**Comment by vncoelho** [comment]
Solved now, @shargon.

![image](https://user-images.githubusercontent.com/17395762/77958757-e4186700-72ab-11ea-884b-a40607e4b379.png)

Thanks.
The `Microsoft.AspNetCore.ResponseCompression.dl` needs to go to the Plugins folder. In fact, it is already described in the Readme.

I need to create a better script for an easier access to it.


Should leave this issue open? Is there a way to make this automatic or simpler?

**Comment by shargon** [comment]
I think that we need dependecies for plugins, this should be automatic.
