### ISSUE TITLE
An exception in RpcNep5Tracker plugin

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-modules#266]
**Describe the bug**
An exception in `RpcNep5Tracker` plugin when transfer `gas` or `neo`.

Details:
```
System.Text.DecoderFallbackException
  HResult=0x80070057
  Message=Unable to translate bytes [FA] at index 0 from specified code page to Unicode.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.Encoding.GetCharCountWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, DecoderNLS decoder)
   at System.Text.Encoding.GetCharCountWithFallback(Byte* pBytesOriginal, Int32 originalByteCount, Int32 bytesConsumedSoFar)
   at System.Text.UTF8Encoding.GetCharCount(Byte* bytes, Int32 count)
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.Encoding.GetString(ReadOnlySpan`1 bytes)
   at Neo.VM.Helper.GetString(StackItem item) in D:\neo_code\neo\src\neo\VM\Helper.cs:line 201
   at Neo.Plugins.RpcNep5Tracker.HandleNotification(StoreView snapshot, IVerifiable scriptContainer, UInt160 scriptHash, Array stateItems, Dictionary`2 nep5BalancesChanged, UInt16& transferIndex) in D:\neo_code\neo-modules\src\RpcNep5Tracker\RpcNep5Tracker.cs:line 110
   at Neo.Plugins.RpcNep5Tracker.OnPersist(StoreView snapshot, IReadOnlyList`1 applicationExecutedList) in D:\neo_code\neo-modules\src\RpcNep5Tracker\RpcNep5Tracker.cs:line 165
   at Neo.Ledger.Blockchain.Persist(Block block) in D:\neo_code\neo\src\neo\Ledger\Blockchain.cs:line 449
   at Neo.Ledger.Blockchain.OnNewBlock(Block block) in D:\neo_code\neo\src\neo\Ledger\Blockchain.cs:line 336
   at Neo.Ledger.Blockchain.OnInventory(IInventory inventory, Boolean relay) in D:\neo_code\neo\src\neo\Ledger\Blockchain.cs:line 303
   at Neo.Ledger.Blockchain.OnReceive(Object message) in D:\neo_code\neo\src\neo\Ledger\Blockchain.cs:line 376
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**To Reproduce**
1. Deploy a neo node and included the `RpcNep5Tracker` plugin;
2. Send a gas transfer transaction;
3. Wait for transaction confirmation and block persist.

**Screenshots**

![image](https://user-images.githubusercontent.com/12728872/85253064-f01d5a80-b48f-11ea-96ba-2f7c81681e4d.png)

**Platform:**
 - OS: Windows 10 x64
 - Version: latest version of master (neo, neo-vm, neo-modules, neo-node)

**Comment by shargon** [comment]
Could you add the steps that you followed?

**Comment by ProDog** [comment]
> Could you add the steps that you followed?

Ok, added.

**Comment by Tommo-L** [comment]
@ProDog  related to https://github.com/neo-project/neo-modules/issues/265
@joeqian10 don't forget to have a check.
