### ISSUE TITLE
bug: can not start RpcServer [v3.0.0-preview2]

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#284]
**Describe the bug**
I'm trying to run single-node (v3.0.0-preview2) C# private network with RPCServer plugin (also v3.0.0-preview2) via neo-cli, but it fails to start. However, node runs perfectly without RPCServer plugin.

**To Reproduce**
1. Download and unzip `neo-cli` v3.0.0-preview2 from [releases](https://github.com/neo-project/neo-node/releases/download/v3.0.0-preview2/neo-cli-linux-x64.zip)
2. Download RPCServer v3.0.0-preview2 plugin from [releases](https://github.com/neo-project/neo-modules/releases/download/v3.0.0-preview2-00/RpcServer.zip)
3. Unzip RPCServer plugin into `neo-cli/Plugins/` folder as described in [guide](https://docs.neo.org/docs/en-us/node/cli/config.html#downloading-plugins-from-github)
4. Setup single-node environment as described in [guide](https://docs.neo.org/v3/docs/en-us/network/private-chain/solo.html#build-a-private-chain-with-one-node)
5. Run `./neo-cli`

As a result, I've got an error:
```
NEO-CLI v3.0.0-preview2  -  NEO v3.0.0-preview2-00  -  NEO-VM v3.0.0-preview2

neo> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.ResponseCompression, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.ResponseCompression, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Neo.Plugins.RpcServer.<>c.<StartRpcServer>b__20_2(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Neo.Plugins.RpcServer.StartRpcServer()
   at Neo.Plugins.RpcServerPlugin.OnPluginsLoaded()
   at Neo.NeoSystem..ctor(String storageEngine)
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Aborted (core dumped)
```

The same thing is happening when I'm trying to install the RPCServer plugin via `./neo-cli install RpcServer`.

**Expected behavior**
Both node and RPC-server are running.

**Platform:**
 - OS: Linux x64
 - Version: both neo-cli-linux-x64 and RpcServer v3.0.0-preview2

**Note**
It seems to me that Microsoft.AspNetCore.ResponseCompression library is missing, so I copied Microsoft.AspNetCore.ResponseCompression.dll from [v3.0.0-preview1 release files](https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview1) and pasted this file to `./neo-cli`. After that there's no problems with starting both node and RPC server.

**Comment by ProDog** [comment]
Seems https://github.com/neo-project/neo-modules/issues/198. 
We need contains Microsoft.AspNetCore.ResponseCompression.dll in neo-cli or RpcServer.

**Comment by roman-khimov** [comment]
Oh, so there is already a bug for it, I think we can close this one then as a duplicate.
