### ISSUE TITLE
Error on RPCServer operation

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#451]
```cs
[00:51:59.211] System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Neo.Plugins.Plugin.LoadPlugin(Assembly assembly) in /opt/neoLib/src/neo/Plugins/Plugin.cs:line 162

System.IO.FileNotFoundException
Could not load file or assembly 'RpcServer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.



[00:51:59.219] System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Neo.Plugins.Plugin.LoadPlugin(Assembly assembly) in /opt/neoLib/src/neo/Plugins/Plugin.cs:line 162

System.IO.FileNotFoundException
Could not load file or assembly 'RpcServer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

Running on a dockerized 4 nodes `mcr.microsoft.com/dotnet/aspnet:5.0.1-focal`

**Comment by chenzhitong** [comment]
Running in Docker will crash, right?
