### ISSUE TITLE
How to broadcast the Nep17 transaction after create it?

### ISSUE THREAD

**Issue by isapi** [neo-project/neo-modules#586]
`...
Nep17API nep17API = new(client);
Transaction tx = await nep17API.CreateTransferTxAsync(UInt160.Parse(contractHash), keyPair, to, 1, data).ConfigureAwait(false);
...
await client.SendRawTransactionAsync(tx) .ConfigureAwait(false);
...`

got error:
`
System.AggregateException: One or more errors occurred. (Invalid)
 ---> Neo.Network.RPC.RpcException: Invalid
   at Neo.Network.RPC.RpcClient.SendAsync(RpcRequest request)
   at Neo.Network.RPC.RpcClient.RpcSendAsync(String method, JObject[] paraArgs)
   at Neo.Network.RPC.RpcClient.SendRawTransactionAsync(Byte[] rawTransaction)
   at N3PRCTest.Program.Broadcast(Transaction trans) in E:\N3PRCTest\N3PRCTest\Program.cs:line 74
   --- End of inner exception stack trace ---
`

**Comment by ProDog** [comment]
Did you load the `config.json` file when you initialized `RpcClient`?  
Or are you loading the same `config.json` file with rpc node?

initialize  `RpcClient`:
```
RpcClient client = new RpcClient(new Uri("http://localhost:10332"), null, null, ProtocolSettings.Load("config.json"));
```
