### ISSUE TITLE
FormatException on tx.attributes

### ISSUE THREAD

**Issue by evgeniygubin** [neo-project/neo-modules#594]
Got block with not-null `attributes` key. It permanent cause `FormatException()` in [`TransactionAttributeFromJson()`](https://github.com/neo-project/neo-modules/blob/6981fc7369fd2029d4991757a0e4e135f80e6f69/src/RpcClient/Utility.cs#L187):

```
System.FormatException: 'One of the identified items was in an invalid format.'

   at Neo.Network.RPC.Utility.TransactionAttributeFromJson(JObject json)
   at Neo.Network.RPC.Utility.<>c.<TransactionFromJson>b__9_1(JObject p)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at Neo.Network.RPC.Utility.TransactionFromJson(JObject json, ProtocolSettings protocolSettings)
   at Neo.Network.RPC.Utility.<>c__DisplayClass6_0.<BlockFromJson>b__0(JObject p)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at Neo.Network.RPC.Utility.BlockFromJson(JObject json, ProtocolSettings protocolSettings)
   at Neo.Network.RPC.Models.RpcBlock.FromJson(JObject json, ProtocolSettings protocolSettings)
   at Neo.Network.RPC.RpcClient.<GetBlockAsync>d__13.MoveNext()
```
![Screenshot 2021-05-28 143103](https://user-images.githubusercontent.com/50550856/119977644-5e806c00-bfc1-11eb-8c55-faa053f0fad6.png)

Don't understand what is the point?
Please tell me if i miss something is documentation.

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai

**Comment by shargon** [comment]
It will be fixed here https://github.com/neo-project/neo-modules/pull/593
(https://github.com/neo-project/neo-modules/pull/593/files#diff-508795ae14ad6b4adf730b4f2bb7ec3b19e9639379883cefd360db0be74b5e0fR192-R199)
